// components/GameCanvas.tsx
import React, { useEffect, useRef, useImperativeHandle, forwardRef } from 'react';
import { GameEngine } from '../utils/gameEngine';

interface GameCanvasProps {
  onScoreUpdate: (score: number) => void;
  onGameOver: (score: number) => void;
}

export interface GameCanvasHandle {
  startGame: () => void;
  handleTap: () => void;
}

const GameCanvas = forwardRef<GameCanvasHandle, GameCanvasProps>((props, ref) => {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const engineRef = useRef<GameEngine | null>(null);

  useImperativeHandle(ref, () => ({
    startGame: () => {
      engineRef.current?.start();
    },
    handleTap: () => {
      engineRef.current?.handleInput();
    }
  }));

  useEffect(() => {
    if (!canvasRef.current) return;

    const engine = new GameEngine(canvasRef.current, {
      onScoreUpdate: props.onScoreUpdate,
      onGameOver: props.onGameOver,
    });
    engineRef.current = engine;

    return () => {
      engine.cleanup();
    };
  }, [props.onScoreUpdate, props.onGameOver]);

  return (
    <canvas
      ref={canvasRef}
      className="block w-full h-full touch-none"
    />
  );
});

GameCanvas.displayName = 'GameCanvas';
export default GameCanvas;

// vue-preview/components/GameCanvas.vue
<template>
  <canvas ref="canvasRef" class="block w-full h-full touch-none" />
</template>

<script lang="ts">
import { defineComponent, onMounted, onBeforeUnmount, ref } from '@nuxtjs/composition-api';
import { GameEngine } from '~/shared/gameEngine';

export default defineComponent({
  name: 'GameCanvas',
  props: {
    boxStyle: {
      type: String,
      default: 'legacy'
    }
  },
  setup(props, { emit }) {
    const canvasRef = ref<HTMLCanvasElement | null>(null);
    let engine: GameEngine | null = null;

    const startGame = () => {
      engine?.start();
    };

    const handleTap = () => {
      engine?.handleInput();
    };

    onMounted(() => {
      if (!canvasRef.value) return;
      engine = new GameEngine(
        canvasRef.value,
        {
          onScoreUpdate: (score: number) => emit('score-update', score),
          onGameOver: (score: number) => emit('game-over', score)
        },
        {
          boxStyle: props.boxStyle as 'legacy' | 'v2'
        }
      );
    });

    onBeforeUnmount(() => {
      engine?.cleanup();
      engine = null;
    });

    return {
      canvasRef,
      startGame,
      handleTap
    };
  }
});
</script>
